server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_reader
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true



  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  logging:
    level:
      org:
        springframework: DEBUG
